# Generated by Django 3.0.1 on 2020-11-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_auto_20201112_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorage',
            name='judul',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
