# Generated by Django 3.0.1 on 2020-11-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filestorage',
            old_name='url',
            new_name='url_dokumen',
        ),
        migrations.AddField(
            model_name='filestorage',
            name='url_sastrawee',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
    ]
